### PR TITLE
Convert readme to markdown

### PR DESCRIPTION
**Pull request by lencioni**
More people are more familiar with this format, and other documents in this repo are in markdown so it seems like a good reason to switch. Additionally, we can get syntax highlighting on github by using fenced code blocks in markdown, which I added in this PR. Rubydoc.info can also handle GitHub flavored markdown now, so everyone wins!

### CODE REVIEW

**Comment by RST-J** [comment]
I don't mind. If everything stays the same (I think I saw broken doc from markdown somewhere once), I actually prefer this.

**Comment by iainbeeston** [comment]
Me too

@lencioni Can you please squash your commits into one?

**Comment by lencioni** [comment]
Sqauashed!

**Comment by iainbeeston** [comment]
Great, thanks!

**Pull request merged**
