### PR TITLE
Fix validator when the specified fragment includes array

### PR DESCRIPTION
**Pull request by take**

### CODE REVIEW

**Comment by jrgns** [comment]
The only failing build is for rbx due to a segmentation fault after the (passing) tests. Is it possible to get this implemented?

**Comment by iainbeeston** [comment]
I need to take a closer look to make sure I understand the implications of this change, and whether it really fixes #265 . I'll try to get this merged and released asap

**Comment by take** [comment]
thx! :D

**Comment by aledalgrande** [comment]
Tried @take-san branch and it worked for me.

**Comment by jrgns** [comment]
@iainbeeston Can we get this resolved? The issue still exists.

**Comment by iainbeeston** [comment]
@jrgns Sure, it's my top priority, but I don't have a lot of time at the moment to dedicate to json-schema. As mentioned in #265 the issue is larger than mentioned here in this PR, and needs a larger fix to truly resolve the issue.

**Comment by iainbeeston** [comment]
I'm planning on adding some more tests and getting this merged after #382

**Comment by iainbeeston** [comment]
I've merged this manually in c12f6000795cc0fdf8d17d97d5bf9c1b383037e4

**Pull request closed without merging**
