### PR TITLE
Show sub-errors for oneOf

### PR DESCRIPTION
**Pull request by isage**
anyOf and allOf show sub-errors.
with this patch oneOf do the same

### CODE REVIEW

**Comment by iainbeeston** [comment]
Great idea, could you add some tests for this similar to those for any of and all of?
(e.g. in test_all_of_ref_schema.rb and test_any_of_ref_schema.rb)

**Comment by iainbeeston** [comment]
Also, this change seems to cause a test failure related to oneOf

**Comment by isage** [comment]
Looking at the test, i'm not sure why it was working before.
insert_defaults will insert foo => "view" into data, so data now matches both variants of oneOf, which should fail.

But still, there's seems to be an error in my patch, because even {foo => view} doesn't seem to validate
I'll try to fix this and write tests

**Comment by isage** [comment]
Oh, okay, i finally get, how test works. "default" inserts value only for one oneOf case, which will fail with strict, and the first one will pass.
I forgot to handle exceptions, that's why it was failing. Now it works.
I'll write tests for oneOf tomorrow

**Comment by isage** [comment]
Okay, i've added tests for sub-errors

**Comment by RST-J** [comment]
Seems fine to me :+1:

**Comment by iainbeeston** [comment]
Ok, I'm happy with this :+1: 

Merging

**Pull request merged**
