### PR TITLE
exception type differs from expected

### PR DESCRIPTION
**Pull request by pkarman**
This test was failing for me locally. Not sure if travis will think the same.

### CODE REVIEW

**Comment by iainbeeston** [comment]
Can you give more details? Like which version of Ruby you're using, and are you running tests with "bundle exec" or without bundler?

**Comment by pkarman** [comment]
Running `rake test` under Ruby 2.2.3 I get the failure. When I run `bundle exec rake test` this PR becomes irrelevant (test passes). I'll close this and just remember to run via bundler. Thanks.

**Comment by iainbeeston** [comment]
This could still be interesting through, I don't suppose you would mind telling me the output from "gem list", so I can see what gems you have installed? (There are few gems that json schema auto defects and uses if they are present - maybe we have an incompatibility with one of them)

**Comment by pkarman** [comment]
```

*** LOCAL GEMS ***

about_yml (0.0.8)
actionmailer (4.2.5, 4.2.4, 4.0.13)
actionpack (4.2.5, 4.2.4, 4.0.13)
actionview (4.2.5, 4.2.4)
active_model_serializers (0.9.4, 0.9.3)
activejob (4.2.5, 4.2.4)
activemodel (4.2.5, 4.2.4, 4.0.13)
activerecord (4.2.5, 4.2.4, 4.0.13)
activerecord-deprecated_finders (1.0.4)
activesupport (4.2.5, 4.2.4, 4.0.13)
acts-as-taggable-on (3.5.0)
acts_as_list (0.7.2)
addressable (2.4.0, 2.3.8)
akami (1.3.1)
ansi (1.5.0)
ar_outer_joins (0.2.0)
arbre (1.0.3)
arel (6.0.3, 4.0.2)
ast (2.2.0, 2.1.0)
astrolabe (1.3.1)
atomic (1.1.99)
autoprefixer-rails (6.2.3, 6.1.1, 6.1.0.1, 6.0.3)
awesome_print (1.6.1)
aws-sdk (1.66.0)
aws-sdk-v1 (1.66.0)
bigdecimal (1.2.6)
bootstrap-sass (3.3.5.1)
bourbon (4.2.6, 4.2.5)
brakeman (3.1.2)
browser-timezone-rails (0.0.8)
builder (3.2.2, 3.1.4)
bullet (4.14.10, 4.14.7)
bundler (1.11.2, 1.10.6)
bundler-audit (0.4.0)
bundler-unload (1.0.2)
byebug (8.2.1, 8.2.0, 8.1.0, 5.0.0)
cane (2.6.2)
capybara (2.5.0)
capybara-webkit (1.7.1)
ci_reporter (1.9.3)
climate_control (0.0.3)
cliver (0.3.2)
clockwork (1.2.0)
cocaine (0.5.8, 0.5.7)
codeclimate-test-reporter (0.4.8)
coderay (1.1.0)
coffee-rails (4.1.1, 4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.10.0, 1.9.1.1)
colorize (0.7.7)
columnize (0.9.0)
concurrent-ruby (1.0.0)
connection_pool (2.2.0)
coveralls (0.8.10)
crack (0.4.3, 0.4.2)
css_parser (1.3.7)
daemons (1.2.3)
database_cleaner (1.5.1, 1.5.0)
debug_inspector (0.0.2)
delayed_job (4.1.1)
delayed_job_active_record (4.1.0)
delayed_job_web (1.2.10)
diff-lcs (1.2.5)
docile (1.1.5)
domain_name (0.5.25)
dotenv (2.0.2)
dotenv-rails (2.0.2)
draper (2.1.0)
elasticsearch (1.0.15)
elasticsearch-api (1.0.15)
elasticsearch-dsl (0.1.3, 0.1.2)
elasticsearch-extensions (0.0.20)
elasticsearch-model (0.1.8)
elasticsearch-rails (0.1.8)
elasticsearch-transport (1.0.15)
email_reply_parser (0.5.8)
email_validator (1.6.0)
erubis (2.7.0)
excon (0.45.4)
execjs (2.6.0)
executable-hooks (1.3.2)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
faker (1.5.0)
faraday (0.9.2, 0.9.1)
faraday_middleware (0.10.0)
fastercsv (1.5.5)
ffi (1.9.10)
flutie (2.0.0)
font-awesome-sass (4.4.0)
foreman (0.78.0)
formatador (0.2.5)
formtastic (3.1.3)
formtastic_i18n (0.4.1)
gem-wrappers (1.2.7)
gherkin (2.12.2)
git-version-bump (0.15.1)
github-markdown (0.6.9)
globalid (0.3.6)
guard (2.13.0)
guard-compat (1.2.1)
guard-rspec (4.6.4)
guard-shell (0.7.1)
gyoku (1.3.1)
haml (4.0.7)
has_scope (0.6.0)
has_secure_token (1.0.0)
hashdiff (0.2.3, 0.2.2)
hashie (3.4.3, 3.4.2)
highline (1.7.8)
hpricot (0.8.6)
html-pipeline (2.2.2, 2.1.0)
html_pipeline_rails (0.1.0)
http-cookie (1.0.2)
httpi (2.4.1)
i18n (0.7.0)
inherited_resources (1.6.0)
io-console (0.4.3)
jquery-rails (4.0.5)
jquery-turbolinks (2.1.0)
jquery-ui-rails (5.0.5)
json (1.8.3, 1.8.1)
json-patch (1.0.0)
json-schema (2.6.0, 2.5.2, 2.5.0)
jwt (1.5.2, 1.5.1)
kaminari (0.16.3)
konacha (3.7.0)
launchy (2.4.3)
letter_opener (1.4.1)
letter_opener_web (1.3.0)
listen (3.0.5, 3.0.4, 3.0.3)
lograge (0.3.5)
loofah (2.0.3)
lumberjack (1.0.9)
mail (2.6.3)
mail_view (2.0.4)
mandrill-rails (1.3.1, 1.3.0)
mechanize (2.7.4)
metaclass (0.0.4)
method_source (0.8.2)
mime-types (2.99, 2.6.2)
mimemagic (0.3.0)
mini_portile (0.6.2)
mini_portile2 (2.0.0)
minitest (5.8.3, 5.8.2, 5.8.1, 4.7.5)
mocha (1.1.0)
multi_json (1.11.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
neat (1.7.2)
nenv (0.2.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
netrc (0.11.0)
newrelic_rpm (3.14.0.305, 3.13.2.302)
nokogiri (1.6.7.2, 1.6.7.1, 1.6.7, 1.6.6.4, 1.6.6.2, 1.6.5)
nori (2.6.0)
normalize-rails (3.0.3)
notiffany (0.0.8)
ntlm-http (0.1.1)
oauth2 (1.0.0)
octokit (3.8.0)
oj (2.14.3)
omniauth (1.2.2)
omniauth-oauth2 (1.4.0, 1.3.1)
paper_trail (4.0.0)
paperclip (4.3.2, 4.3.1)
parallel (1.6.1)
paranoia (2.1.3)
parser (2.2.3.0, 2.2.2.6)
peek (0.1.10)
peek-delayed_job (0.1.1, 0.1.0)
peek-performance_bar (1.2.0)
peek-pg (1.1.0)
pg (0.18.4, 0.18.3)
poltergeist (1.8.1, 1.8.0, 1.7.0, 1.6.0)
polyamorous (1.2.0)
power_assert (0.2.6)
powerpack (0.1.1)
pry (0.10.3, 0.10.2)
pry-byebug (3.3.0, 3.2.0)
pry-rails (0.3.4)
psych (2.0.8)
puma (2.15.3, 2.14.0)
pundit (1.0.1)
queryparams (0.0.3)
quiet_assets (1.1.0)
rack (1.6.4, 1.5.5)
rack-canonical-host (0.1.0)
rack-contrib (1.4.0)
rack-cors (0.4.0)
rack-protection (1.5.3)
rack-test (0.6.3)
rack-timeout (0.3.2)
rack_session_access (0.1.1)
railroady (1.4.1, 1.3.1)
rails (4.2.5, 4.2.4, 4.0.13)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.4)
rails_stdout_logging (0.0.4)
railties (4.2.5, 4.2.4, 4.0.13)
rainbow (2.0.0)
rake (10.4.2)
ransack (1.7.0)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rdoc (4.2.0)
redcarpet (3.3.4, 3.3.3)
redis (3.2.2)
refills (0.1.0)
request_store (1.2.1, 1.2.0)
require-prof (0.0.1)
responders (2.1.0)
rest-client (1.8.0)
roadie (3.1.0, 3.0.5)
roadie-rails (1.1.0, 1.0.6)
rspec (3.4.0, 3.3.0)
rspec-core (3.4.1, 3.3.2)
rspec-expectations (3.4.0, 3.3.1)
rspec-mocks (3.4.0, 3.3.2)
rspec-rails (3.4.0, 3.3.3)
rspec-support (3.4.1, 3.3.0)
rspec_junit_formatter (0.2.3)
rubocop (0.35.1, 0.34.2)
ruby-prof (0.15.9)
ruby-progressbar (1.7.5)
ruby2ruby (2.2.0)
ruby_parser (3.7.2)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
safe_yaml (1.0.4)
sass (3.4.20, 3.4.19, 3.4.18)
sass-rails (5.0.4)
savon (2.11.1)
sawyer (0.6.0)
sexp_processor (4.6.0)
shellany (0.0.1)
shoulda-context (1.2.1)
shoulda-matchers (3.1.0, 3.0.1)
sidekiq (4.0.2)
simple_form (3.2.1, 3.2.0)
simple_form_object (0.0.8)
simplecov (0.11.1, 0.10.0)
simplecov-html (0.10.0)
sinatra (1.4.6)
site_prism (2.8)
slim (3.0.6)
slop (3.6.0)
spring (1.6.2, 1.4.4, 1.4.1, 1.4.0)
spring-commands-rspec (1.0.4)
sprockets (3.5.2, 3.4.0)
sprockets-rails (3.0.0, 2.3.3)
sqlite3 (1.3.11)
temping (3.3.0)
temple (0.7.6)
term-ansicolor (1.3.2)
terminal-table (1.5.2)
test-unit (3.1.7, 3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.2, 2.0.1)
timecop (0.8.0)
tins (1.6.0)
title (0.0.5)
tourbus (2.0.2)
trollop (2.1.2)
turbolinks (2.5.3)
turn (0.9.7)
turnip (1.3.1)
tzinfo (1.2.2, 0.3.46)
uglifier (2.7.2)
unf (0.1.4)
unf_ext (0.0.7.1)
uniform_notifier (1.9.0)
us_web_design_standards (0.0.2)
validates_email_format_of (1.6.3)
vcr (3.0.1)
wasabi (3.5.0)
web-console (3.0.0)
webmock (1.22.6, 1.22.3, 1.21.0)
webrat (0.7.3)
webrobots (0.1.2)
websocket-driver (0.6.3, 0.6.2)
websocket-extensions (0.1.2)
workflow (1.2.0)
xpath (2.0.0)
yard (0.8.7.6)
zonebie (0.5.1)
```

**Comment by pkarman** [comment]
updating `rake` to 10.5.0 seems to have helped.

**Pull request closed without merging**
