### PR TITLE
Support Draft 7

### PR DESCRIPTION
**Pull request by Martouta**
Support Draft 7. Not all of it but it means to support what we need for https://github.com/3scale/porta/pull/593

### CODE REVIEW

**Comment by heynan0** [comment]
I think someone could build upon your work here to support more drafts.

**Comment by Martouta** [comment]
@heynan0 you should check https://github.com/voxpupuli/json-schema/issues/423 and https://github.com/davishmcclurg/json_schemer

**Comment by Martouta** [comment]
btw, that info may also be useful for @secretsurf @josemigallas (assuming that you are still part of the 3scale system/porta team) ☝🏼

TL;DR: This repo/gem is not really thaaaat maintained anymore (kinda looking for maintainers) and does not support new draft versions but the other repo/gem does.

**Comment by bastelfreak** [comment]
Hi, we are happy to review new patches for the project and would also accept new maintainers :)

**Pull request closed without merging**
