### PR TITLE
Expose clear_cache option

### PR DESCRIPTION
**Pull request by danieldraper**
This pull-request is to fix https://github.com/ruby-json-schema/json-schema/issues/225

### CODE REVIEW

**Comment by iainbeeston** [comment]
Travis is failing, after this change (not sure why this would cause it to fail however)

**Comment by iainbeeston** [comment]
If we can figure out why the build is failing it gets my :+1:

**Comment by hoxworth** [comment]
Build is passing now, :+1:

**Comment by iainbeeston** [comment]
Thanks @hoxworth . Merging...

**Pull request merged**
